main: me.rayzr522.permissioneffects.PermissionEffects
name: PermissionEffects
version: ${project.version}
description: ${project.description}
author: Rayzr
commands:
  permissioneffects:
    description: The main command for PermissionEffects
    aliases: [pe]
    usage: "\u00A7cRayzr screwed up."